### ISSUE TITLE
+[BatchPush handleNotification:] is not deprecated

### ISSUE THREAD

**Issue by ghugues** [BatchLabs/Batch-iOS-SDK#27] opened 2021-06-12 10:20 UTC
## Summary 
`+[BatchPush handleNotification:]` has been marked as deprecated in recent versions of the SDK. However, in manual integration, it must be called from `application:didReceiveRemoteNotification:fetchCompletionHandler:` which is not deprecated.

## Reproduction steps
1. Implement the SDK using manual integration
2. Call `+[BatchPush handleNotification:]` from `application:didReceiveRemoteNotification:fetchCompletionHandler:`
3. A deprecated warning is issued by the compiler

### SDK Version
1.17.2
### Installation method
CocoaPods
### Relevant development tools versions
Xcode 12.4

**Comment by abarisain** [comment] 2021-06-12 11:52
Hello,
Thanks for your feedback.

As of Batch 1.16, integration of Batch in any `application:didReceiveRemoteNotification` variant isn't required as we 100% rely on UNUserNotificationCenterDelegate. You can safely remove this call.

We'll check the documentation on monday and see if it needs tweaking.

Have a great day,

**Comment by ghugues** [comment] 2021-06-12 13:02
Hello,

To my knowledge, background fetch pushes (those with content-available: 1 and no alert, sound or badge) never go through `UNUserNotificationCenterDelegate`, they only trigger `application:didReceiveRemoteNotification:fetchCompletionHandler:`.

However, looking at the code, it seems that the SDK carefully identifies these pushes in order to ignore them. Which actually makes sense since there is not much the SDK can do with them. I was expecting the SDK to still do some kind of reporting in order to have a sort of "open rate" on the backend, but it does not seem to be the case.

Feel free to close this issue if this is all intended behavior.

Best regards,

**Comment by abarisain** [comment] 2021-06-12 13:15
You're right: those pushes don't go through  UNUserNotificationCenterDelegate. Like you said, the SDK wants to ignore them.
The UN...Delegate only telling us about visible notifications while not mixing in background pushes is actually a feature for us, as detecting the current app state got way messier with UIScene.

We do report opens, but we only for user visible notifications. This is by design for both a technical reason — as we do not want to make extra network calls when your app is in the background as iOS monitors this — and a product decision.

If we add features requiring that the SDK knows about background pushes, we'll mention it in the changelog and add a specialized method to BatchPush.

I'll be closing this as this is expected behaviour.
Thanks again for the report!

Best,

**Closed by abarisain** 2021-06-12 13:15 UTC
Labels: bug
