### ISSUE TITLE
Lack of escaping breaks slicing script.

### ISSUE THREAD

**Issue by acoye** [BatchLabs/Batch-iOS-SDK#19] opened 2019-08-05 15:23 UTC
### Description 

`BatchExtension.framework/strip-frameworks.sh` will fail if your app contains a space in its path. Like `Acme app.app/…`

### Possible solution

A quick and dirty escaping in sed is what I used to fix the issue. `sed 's/ /\\ /g'`

Thanks.

**Comment by abarisain** [comment] 2019-08-05 15:24
Thanks, we'll fix the script in the next release.

The script is going away in september anyway, as we're moving to XCFrameworks

**Comment by acoye** [comment] 2019-08-05 15:29
Alright thanks 👍

**Comment by abarisain** [comment] 2019-08-05 16:11
Hello again,

I just remembered that we have an internal project with a space in it's name, and it works fine. The framework has been integrated manually, without Cocoapods nor Carthage.

Where did you apply the sed command? I'm trying to reproduce the issue on my end.

**Comment by acoye** [comment] 2019-08-07 15:38
Hey, sure I can give you more details.

As I needed to use `BatchExtension.framework` in a project relying on cocoapods I wrapped it in a private pod I now manage internally. So that might be why you cannot reproduce.

I applied the sed command on `${FRAMEWORKS_FOLDER_PATH}` where the unescaped space broke it.

I'm also happy to know you work on `XCFrameworks` as this is a good news for my integration efforts.

**Comment by abarisain** [comment] 2019-08-08 14:40
Oh it may be because of the pods alright. We'll check that out, thanks for the information!

Regarding XCFrameworks, I just hope that we won't become temporarily incompatible with cocoapods: Carthage gave signs of XCFrameworks implementation, and I don't see anything from Cocoapods yet...

**Comment by abarisain** [comment] 2020-11-04 17:08
Closing this: The binary BatchExtension has been deprecated.

The new extension is open-source: https://github.com/BatchLabs/Batch-iOS-SDK-Extension , which removes the need for such scripts.

Please see our documentation for migration steps: https://doc.batch.com/ios/advanced/1_16-migration

**Closed by abarisain** 2020-11-04 17:08 UTC

**Comment by acoye** [comment] 2020-11-05 14:27
@abarisain I was actually about to update the SDK. Good to hear the extension is opensource now 👍
Thanks for closing the issue with a detailed message.
